exclude: ["Rakefile", "README.md"]
encoding: utf-8
timezone: America/Los_Angeles

defaults:
    -
        scope:
            path: "blog"
            type: "posts"
        values:
            layout: "blog"
            permalink: /blog/:year/:month/:day/:title.html
