exclude: ["Rakefile", "README.md"]
encoding: utf-8
timezone: America/Los_Angeles

url: http://jesterpm.net

defaults:
    -
        scope:
            path: "blog"
            type: "posts"
        values:
            layout: "blog"
            permalink: /blog/:year/:month/:day/:title.html
    -
        scope:
            path: "projects"
            type: "posts"
        values:
            layout: "project"
            permalink: /projects/:title.html

prose:
    media: "images"

sass:
    sass_dir: _sass
    style: :compressed
